# Generated by Django 4.1 on 2023-02-06 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allo_doc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscription',
        ),
    ]
