# Generated by Django 4.1 on 2023-02-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allo_doc', '0004_alter_appointment_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='prenom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
