# Generated by Django 4.1 on 2023-02-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allo_doc', '0005_appointment_nom_appointment_prenom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('jour_rdv', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
    ]
